// Code generated by funcs-gen. DO NOT EDIT.
package funcs

import (
	"github.com/katydid/parser-go/parse"
	"github.com/katydid/validator-go/validator/ast"
)

type varDouble struct {
	Value parse.Token
	hash  uint64
}

var _ Setter = &varDouble{}
var _ aVariable = &varDouble{}

type ErrNotDoubleConst struct{}

func (this ErrNotDoubleConst) Error() string {
	return "$double is not a const"
}

func (this *varDouble) Compare(that Comparable) int {
	if this.Hash() != that.Hash() {
		if this.Hash() < that.Hash() {
			return -1
		}
		return 1
	}
	if _, ok := that.(*varDouble); ok {
		return 0
	}
	return this.ToExpr().Compare(that.ToExpr())
}

func (this *varDouble) Hash() uint64 {
	return this.hash
}

func (this *varDouble) HasVariable() bool { return true }

func (this *varDouble) isVariable() {}

func (this *varDouble) SetValue(v parse.Token) {
	this.Value = v
}

func (this *varDouble) ToExpr() *ast.Expr {
	return ast.NewDoubleVar()
}

// DoubleVar returns a variable of type Double
func DoubleVar() *varDouble {
	h := uint64(17)
	h = 31*h + 2052876273
	return &varDouble{hash: h}
}

type varInt struct {
	Value parse.Token
	hash  uint64
}

var _ Setter = &varInt{}
var _ aVariable = &varInt{}

type ErrNotIntConst struct{}

func (this ErrNotIntConst) Error() string {
	return "$int is not a const"
}

func (this *varInt) Compare(that Comparable) int {
	if this.Hash() != that.Hash() {
		if this.Hash() < that.Hash() {
			return -1
		}
		return 1
	}
	if _, ok := that.(*varInt); ok {
		return 0
	}
	return this.ToExpr().Compare(that.ToExpr())
}

func (this *varInt) Hash() uint64 {
	return this.hash
}

func (this *varInt) HasVariable() bool { return true }

func (this *varInt) isVariable() {}

func (this *varInt) SetValue(v parse.Token) {
	this.Value = v
}

func (this *varInt) ToExpr() *ast.Expr {
	return ast.NewIntVar()
}

// IntVar returns a variable of type Int
func IntVar() *varInt {
	h := uint64(17)
	h = 31*h + 73679
	return &varInt{hash: h}
}

type varUint struct {
	Value parse.Token
	hash  uint64
}

var _ Setter = &varUint{}
var _ aVariable = &varUint{}

type ErrNotUintConst struct{}

func (this ErrNotUintConst) Error() string {
	return "$uint is not a const"
}

func (this *varUint) Compare(that Comparable) int {
	if this.Hash() != that.Hash() {
		if this.Hash() < that.Hash() {
			return -1
		}
		return 1
	}
	if _, ok := that.(*varUint); ok {
		return 0
	}
	return this.ToExpr().Compare(that.ToExpr())
}

func (this *varUint) Hash() uint64 {
	return this.hash
}

func (this *varUint) HasVariable() bool { return true }

func (this *varUint) isVariable() {}

func (this *varUint) SetValue(v parse.Token) {
	this.Value = v
}

func (this *varUint) ToExpr() *ast.Expr {
	return ast.NewUintVar()
}

// UintVar returns a variable of type Uint
func UintVar() *varUint {
	h := uint64(17)
	h = 31*h + 2636666
	return &varUint{hash: h}
}

type varBool struct {
	Value parse.Token
	hash  uint64
}

var _ Setter = &varBool{}
var _ aVariable = &varBool{}

type ErrNotBoolConst struct{}

func (this ErrNotBoolConst) Error() string {
	return "$bool is not a const"
}

func (this *varBool) Compare(that Comparable) int {
	if this.Hash() != that.Hash() {
		if this.Hash() < that.Hash() {
			return -1
		}
		return 1
	}
	if _, ok := that.(*varBool); ok {
		return 0
	}
	return this.ToExpr().Compare(that.ToExpr())
}

func (this *varBool) Hash() uint64 {
	return this.hash
}

func (this *varBool) HasVariable() bool { return true }

func (this *varBool) isVariable() {}

func (this *varBool) SetValue(v parse.Token) {
	this.Value = v
}

func (this *varBool) ToExpr() *ast.Expr {
	return ast.NewBoolVar()
}

// BoolVar returns a variable of type Bool
func BoolVar() *varBool {
	h := uint64(17)
	h = 31*h + 2076426
	return &varBool{hash: h}
}

type varString struct {
	Value parse.Token
	hash  uint64
}

var _ Setter = &varString{}
var _ aVariable = &varString{}

type ErrNotStringConst struct{}

func (this ErrNotStringConst) Error() string {
	return "$string is not a const"
}

func (this *varString) Compare(that Comparable) int {
	if this.Hash() != that.Hash() {
		if this.Hash() < that.Hash() {
			return -1
		}
		return 1
	}
	if _, ok := that.(*varString); ok {
		return 0
	}
	return this.ToExpr().Compare(that.ToExpr())
}

func (this *varString) Hash() uint64 {
	return this.hash
}

func (this *varString) HasVariable() bool { return true }

func (this *varString) isVariable() {}

func (this *varString) SetValue(v parse.Token) {
	this.Value = v
}

func (this *varString) ToExpr() *ast.Expr {
	return ast.NewStringVar()
}

// StringVar returns a variable of type String
func StringVar() *varString {
	h := uint64(17)
	h = 31*h + 2486848561
	return &varString{hash: h}
}

type varBytes struct {
	Value parse.Token
	hash  uint64
}

var _ Setter = &varBytes{}
var _ aVariable = &varBytes{}

type ErrNotBytesConst struct{}

func (this ErrNotBytesConst) Error() string {
	return "$[]byte is not a const"
}

func (this *varBytes) Compare(that Comparable) int {
	if this.Hash() != that.Hash() {
		if this.Hash() < that.Hash() {
			return -1
		}
		return 1
	}
	if _, ok := that.(*varBytes); ok {
		return 0
	}
	return this.ToExpr().Compare(that.ToExpr())
}

func (this *varBytes) Hash() uint64 {
	return this.hash
}

func (this *varBytes) HasVariable() bool { return true }

func (this *varBytes) isVariable() {}

func (this *varBytes) SetValue(v parse.Token) {
	this.Value = v
}

func (this *varBytes) ToExpr() *ast.Expr {
	return ast.NewBytesVar()
}

// BytesVar returns a variable of type Bytes
func BytesVar() *varBytes {
	h := uint64(17)
	h = 31*h + 64671819
	return &varBytes{hash: h}
}
