// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"github.com/katydid/validator-go/validator/token"
)

const (
	NoState    = -1
	NumStates  = 272
	NumSymbols = 198
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '('
1: ')'
2: '0'
3: '-'
4: '('
5: ')'
6: '('
7: '-'
8: ')'
9: '$'
10: '$'
11: '$'
12: '$'
13: '$'
14: '$'
15: '{'
16: ','
17: '}'
18: '<'
19: 'e'
20: 'm'
21: 'p'
22: 't'
23: 'y'
24: '>'
25: '['
26: ']'
27: 'b'
28: 'o'
29: 'o'
30: 'l'
31: '['
32: ']'
33: 'i'
34: 'n'
35: 't'
36: '['
37: ']'
38: 'u'
39: 'i'
40: 'n'
41: 't'
42: '['
43: ']'
44: 'd'
45: 'o'
46: 'u'
47: 'b'
48: 'l'
49: 'e'
50: '['
51: ']'
52: 's'
53: 't'
54: 'r'
55: 'i'
56: 'n'
57: 'g'
58: '['
59: ']'
60: '['
61: ']'
62: 'b'
63: 'y'
64: 't'
65: 'e'
66: 't'
67: 'r'
68: 'u'
69: 'e'
70: 'f'
71: 'a'
72: 'l'
73: 's'
74: 'e'
75: '='
76: '('
77: ')'
78: '{'
79: '}'
80: ','
81: ';'
82: '#'
83: '&'
84: '|'
85: '['
86: ']'
87: ':'
88: '!'
89: '*'
90: '_'
91: '.'
92: '@'
93: '-'
94: '>'
95: '='
96: '='
97: '!'
98: '='
99: '<'
100: '>'
101: '<'
102: '='
103: '>'
104: '='
105: ':'
106: ':'
107: '?'
108: '~'
109: '/'
110: '/'
111: '\n'
112: '/'
113: '*'
114: '*'
115: '*'
116: '/'
117: ' '
118: '\t'
119: '\n'
120: '\r'
121: '0'
122: '0'
123: 'x'
124: 'X'
125: '-'
126: 'e'
127: 'E'
128: '+'
129: '-'
130: '.'
131: '.'
132: '.'
133: '_'
134: '_'
135: 'd'
136: 'o'
137: 'u'
138: 'b'
139: 'l'
140: 'e'
141: 'i'
142: 'n'
143: 't'
144: 'u'
145: 'i'
146: 'n'
147: 't'
148: '['
149: ']'
150: 'b'
151: 'y'
152: 't'
153: 'e'
154: 's'
155: 't'
156: 'r'
157: 'i'
158: 'n'
159: 'g'
160: 'b'
161: 'o'
162: 'o'
163: 'l'
164: '.'
165: '\'
166: 'U'
167: '\'
168: 'u'
169: '\'
170: 'x'
171: '\'
172: '`'
173: '`'
174: '\'
175: 'a'
176: 'b'
177: 'f'
178: 'n'
179: 'r'
180: 't'
181: 'v'
182: '\'
183: '''
184: '"'
185: '"'
186: '"'
187: '''
188: '''
189: '0'-'9'
190: '0'-'7'
191: '0'-'9'
192: 'A'-'F'
193: 'a'-'f'
194: '1'-'9'
195: 'A'-'Z'
196: 'a'-'z'
197: .
*/
