// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"github.com/katydid/validator-go/validator/token"
)

const (
	NoState    = -1
	NumStates  = 290
	NumSymbols = 210
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '('
1: ')'
2: '0'
3: '-'
4: '('
5: ')'
6: '('
7: '-'
8: ')'
9: '$'
10: '$'
11: '$'
12: '$'
13: '$'
14: '$'
15: '$'
16: '{'
17: ','
18: '}'
19: '('
20: ')'
21: '<'
22: 'e'
23: 'm'
24: 'p'
25: 't'
26: 'y'
27: '>'
28: '['
29: ']'
30: 'b'
31: 'o'
32: 'o'
33: 'l'
34: '['
35: ']'
36: 'i'
37: 'n'
38: 't'
39: '['
40: ']'
41: 'u'
42: 'i'
43: 'n'
44: 't'
45: '['
46: ']'
47: 'd'
48: 'o'
49: 'u'
50: 'b'
51: 'l'
52: 'e'
53: '['
54: ']'
55: 's'
56: 't'
57: 'r'
58: 'i'
59: 'n'
60: 'g'
61: '['
62: ']'
63: '['
64: ']'
65: 'b'
66: 'y'
67: 't'
68: 'e'
69: '['
70: ']'
71: 't'
72: 'a'
73: 'g'
74: 't'
75: 'r'
76: 'u'
77: 'e'
78: 'f'
79: 'a'
80: 'l'
81: 's'
82: 'e'
83: '='
84: '('
85: ')'
86: '{'
87: '}'
88: ','
89: ';'
90: '#'
91: '&'
92: '|'
93: '['
94: ']'
95: ':'
96: '!'
97: '*'
98: '_'
99: '.'
100: '@'
101: '-'
102: '>'
103: '='
104: '='
105: '!'
106: '='
107: '<'
108: '>'
109: '<'
110: '='
111: '>'
112: '='
113: ':'
114: ':'
115: '?'
116: '~'
117: '^'
118: '/'
119: '/'
120: '\n'
121: '/'
122: '*'
123: '*'
124: '*'
125: '/'
126: ' '
127: '\t'
128: '\n'
129: '\r'
130: '0'
131: '0'
132: 'x'
133: 'X'
134: '-'
135: 'e'
136: 'E'
137: '+'
138: '-'
139: '.'
140: '.'
141: '.'
142: '_'
143: '_'
144: 'd'
145: 'o'
146: 'u'
147: 'b'
148: 'l'
149: 'e'
150: 'i'
151: 'n'
152: 't'
153: 'u'
154: 'i'
155: 'n'
156: 't'
157: '['
158: ']'
159: 'b'
160: 'y'
161: 't'
162: 'e'
163: 's'
164: 't'
165: 'r'
166: 'i'
167: 'n'
168: 'g'
169: 'b'
170: 'o'
171: 'o'
172: 'l'
173: 't'
174: 'a'
175: 'g'
176: '.'
177: '\'
178: 'U'
179: '\'
180: 'u'
181: '\'
182: 'x'
183: '\'
184: '`'
185: '`'
186: '\'
187: 'a'
188: 'b'
189: 'f'
190: 'n'
191: 'r'
192: 't'
193: 'v'
194: '\'
195: '''
196: '"'
197: '"'
198: '"'
199: '''
200: '''
201: '0'-'9'
202: '0'-'7'
203: '0'-'9'
204: 'A'-'F'
205: 'a'-'f'
206: '1'-'9'
207: 'A'-'Z'
208: 'a'-'z'
209: .
*/
