// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"github.com/katydid/validator-go/validator/token"
)

const (
	NoState    = -1
	NumStates  = 289
	NumSymbols = 209
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '('
1: ')'
2: '0'
3: '-'
4: '('
5: ')'
6: '('
7: '-'
8: ')'
9: '$'
10: '$'
11: '$'
12: '$'
13: '$'
14: '$'
15: '$'
16: '{'
17: ','
18: '}'
19: '('
20: ')'
21: '<'
22: 'e'
23: 'm'
24: 'p'
25: 't'
26: 'y'
27: '>'
28: '['
29: ']'
30: 'b'
31: 'o'
32: 'o'
33: 'l'
34: '['
35: ']'
36: 'i'
37: 'n'
38: 't'
39: '['
40: ']'
41: 'u'
42: 'i'
43: 'n'
44: 't'
45: '['
46: ']'
47: 'd'
48: 'o'
49: 'u'
50: 'b'
51: 'l'
52: 'e'
53: '['
54: ']'
55: 's'
56: 't'
57: 'r'
58: 'i'
59: 'n'
60: 'g'
61: '['
62: ']'
63: '['
64: ']'
65: 'b'
66: 'y'
67: 't'
68: 'e'
69: '['
70: ']'
71: 't'
72: 'a'
73: 'g'
74: 't'
75: 'r'
76: 'u'
77: 'e'
78: 'f'
79: 'a'
80: 'l'
81: 's'
82: 'e'
83: '='
84: '('
85: ')'
86: '{'
87: '}'
88: ','
89: ';'
90: '#'
91: '&'
92: '|'
93: '['
94: ']'
95: ':'
96: '!'
97: '*'
98: '_'
99: '.'
100: '@'
101: '-'
102: '>'
103: '='
104: '='
105: '!'
106: '='
107: '<'
108: '>'
109: '<'
110: '='
111: '>'
112: '='
113: ':'
114: ':'
115: '?'
116: '~'
117: '/'
118: '/'
119: '\n'
120: '/'
121: '*'
122: '*'
123: '*'
124: '/'
125: ' '
126: '\t'
127: '\n'
128: '\r'
129: '0'
130: '0'
131: 'x'
132: 'X'
133: '-'
134: 'e'
135: 'E'
136: '+'
137: '-'
138: '.'
139: '.'
140: '.'
141: '_'
142: '_'
143: 'd'
144: 'o'
145: 'u'
146: 'b'
147: 'l'
148: 'e'
149: 'i'
150: 'n'
151: 't'
152: 'u'
153: 'i'
154: 'n'
155: 't'
156: '['
157: ']'
158: 'b'
159: 'y'
160: 't'
161: 'e'
162: 's'
163: 't'
164: 'r'
165: 'i'
166: 'n'
167: 'g'
168: 'b'
169: 'o'
170: 'o'
171: 'l'
172: 't'
173: 'a'
174: 'g'
175: '.'
176: '\'
177: 'U'
178: '\'
179: 'u'
180: '\'
181: 'x'
182: '\'
183: '`'
184: '`'
185: '\'
186: 'a'
187: 'b'
188: 'f'
189: 'n'
190: 'r'
191: 't'
192: 'v'
193: '\'
194: '''
195: '"'
196: '"'
197: '"'
198: '''
199: '''
200: '0'-'9'
201: '0'-'7'
202: '0'-'9'
203: 'A'-'F'
204: 'a'-'f'
205: '1'-'9'
206: 'A'-'Z'
207: 'a'-'z'
208: .
*/
